# web-test-app/docker-compose.yml

version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: unless-stopped
        volumes:
            - ./frontend:/var/www/front
            - /var/www/front/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:80"
        networks:
            - app-network

    # Laravel Backend Service
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        working_dir: /var/www/html
        restart: unless-stopped
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        ports:
            - "9000:80"
        tty: true
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - db
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./backend:/var/www/html
            - ./frontend:/var/www/front
            - ./source/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend
        networks:
            - app-network

    # Postgres DB
    db:
        image: postgres:14.2
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./source/postgres/postgresdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
