# web-test-app/docker-compose.yml

version: "3.8"

services:
    # Laravel Backend Service
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        working_dir: /var/www
        restart: unless-stopped
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        ports:
            - "9000:80"
        tty: true
        volumes:
            - .:/var/www
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: postgres:14.2
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
