version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: postgres:14.2
        container_name: db
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        expose:
            - "5432" # Publishes 5432 to other containers but NOT to host machine
        ports:
            - "5432:5432"
        command: -p 5432
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
